[package]
name = "cache-server"
version = "0.1.0"

[dependencies]
mio = "0.6"
crossbeam = "0.3"
num_cpus = "1.0"
chrono = "0.4"
glob = "0.2"
tokio = { version = "1", features = ["full"] }
clap = "2.33"
futures-util = "0.3"
